enum RequestState {
  SUCCESS,
  ERROR_USER_EXISTS,
  ERROR_WRONG_CREDENTIALS,
  ERROR_CONFIRMATION_NECESSARY,
  ERROR_WRONG_CODE,
  ERROR_EXPIRED_CODE,
  ERROR_USER_UNKNOWN,
  ERROR_TIMEOUT,
  ERROR_FAILED,
  ERROR_NOT_LOGGED_IN,
  ERROR_FAILED_NO_INTERNET
}
