source "https://rubygems.org"

#gem "cocoapods", "1.10.1"
gem "cocoapods", "1.14.0"
gem "xcode-install", "2.7.0"
#gem 'activesupport', '>= 6.1.7.3', '< 7.1.0'
gem 'activesupport', '>= 7.0.8'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
